config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # Defines the root path route ("/")
  # root "articles#index"

  authenticated :user do
    root 'posts#index'
  end

  resources :posts

  unauthenticated :account do
    root to: redirect('/users/sign_in'), as: :unauthenticated_root
  end

  get 'home', to: redirect('/')

  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"
  get "/offline" => "service_worker#offline"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, :content

  after_create_commit { broadcast_append_to 'posts' }
  after_update_commit { broadcast_replace_to 'posts' }
  after_destroy_commit { broadcast_remove_to 'posts' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  # index
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/service_worker_controller.rb
class ServiceWorkerController < ApplicationController
  protect_from_forgery except: :service_worker

  # service worker
  def service_worker; end

  # manifest
  def manifest; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_pwa_assets.html.erb
<link rel="manifest" crossorigin="use-credentials" href="/manifest.json" />
<meta name="theme-color" content="#2196f3"/>
<link rel="apple-touch-icon" href="<%= asset_path 'icons/apple-icon-180.png'%> ">
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2048-2732.jpg' %>" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2732-2048.jpg' %>" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1668-2388.jpg' %>" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2388-1668.jpg' %>" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1536-2048.jpg' %>" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2048-1536.jpg' %>" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1668-2224.jpg' %>" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2224-1668.jpg' %>" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1620-2160.jpg' %>" media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2160-1620.jpg' %>" media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1290-2796.jpg' %>" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2796-1290.jpg' %>" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1179-2556.jpg' %>" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2556-1179.jpg' %>" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1284-2778.jpg' %>" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2778-1284.jpg' %>" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1170-2532.jpg' %>" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2532-1170.jpg' %>" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1125-2436.jpg' %>" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2436-1125.jpg' %>" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1242-2688.jpg' %>" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2688-1242.jpg' %>" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-828-1792.jpg' %>" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1792-828.jpg' %>" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1242-2208.jpg' %>" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-2208-1242.jpg' %>" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-750-1334.jpg' %>" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1334-750.jpg' %>" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-640-1136.jpg' %>" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
<link rel="apple-touch-startup-image" href="<%= asset_path 'icons/apple-splash-1136-640.jpg' %>" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PwaRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# assets for pwa %>
    <%= render partial: "layouts/pwa_assets"%>
  </head>
  <body class="text-gray-900 dark:text-gray-100 bg-gray-100 dark:bg-zinc-900">
    <main class="container mx-auto">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
  <div class="rounded-xl bg-white p-6 my-8 first:mt-2 dark:bg-zinc-800">
    <h2 class="text-xl"> <%= post.title %> </h2>
    <p> <%= post.content %> </p>
    <div class="flex justify-end">
      <div>
        <p class="text-end text-sm"> <%= post.user.email %> </p>
        <p class="text-end text-xs text-gray-500">
          <% if (Time.zone.now.to_date - post.created_at.to_date).to_i > 1 %>
            <%= post.created_at.strftime('%b %d, %Y') %>
          <% else %>
            <%= time_ago_in_words(post.created_at) %> ago
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= render partial: "shared/navbar"%>
<div class="px-2 sm:px-4">
  <h1 class="text-2xl font-medium"> Posts </h1>
</div>
<div class="px-2 sm:px-4">
  <%= turbo_stream_from "posts" %>
  <%= turbo_frame_tag "posts" do %>
    <%= render @posts %>
  <% end %>
</div>

app/views/service_worker/manifest.json.erb
{
  "short_name": "pwa",
  "name": "PWA Rails",
  "id": "/",
  "icons": [
    {
      "src": "<%= image_path 'icons/manifest-icon-192.maskable.png' %>",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "any"
    },
    {
      "src": "<%= image_path 'icons/manifest-icon-192.maskable.png' %>",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "<%= image_path 'icons/manifest-icon-512.maskable.png' %>",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "any"
    },
    {
      "src": "<%= image_path 'icons/manifest-icon-512.maskable.png' %>",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ],
  "start_url": "/",
  "background_color": "#2196f3",
  "display": "standalone",
  "scope": "/",
  "theme_color": "#2196f3"
}

app/views/service_worker/offline.html.erb
<h1>You Are Offline</h1>

app/views/shared/_navbar.html.erb
<nav class="border-gray-200 px-2 sm:px-4 py-2.5 my-2">
  <div class="container flex flex-wrap items-center justify-between mx-auto">
    <%= link_to root_path, class: "text-2xl font-medium", data: { turbo: false } do %>
      Home
    <% end %>
    <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
      Logout
    <% end %>
  </div>
</nav>

app/views/template/auth.html.erb
<div class="flex flex-col justify-center items-center pt-10">
  <%= content_for?(:content) ? yield(:content) : "" %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>